version: "3.8"

x-shared-config: &shared-config
  # Comment previous line and uncomment following lines to recompile docker image
  build:
    context: .
    dockerfile: ./docker/Dockerfile
    args:
      BUNDLER_VERSION: "1.17.3"
      NODE_MAJOR: "12"
      RUBY_VERSION: "2.6.5"
  tmpfs:
    - /tmp
  stdin_open: true
  tty: true
  volumes:
    - .:/website:cached
    - ./docker/.bashrc:/root/.bashrc:ro
    - ./docker/.irbrc:/root/.irbrc:ro
    - ./docker/.psqlrc:/root/.psqlrc:ro
    - base_cache_rails:/app/tmp/cache
    - base_gems:/usr/src/gems
    - base_packs:/website/public/packs

  env_file:
    - ./docker/postgres/.env
    - ./docker/.env

  environment:
    - POSTGRES_HOST=postgres
  depends_on:
    - postgres
    - redis
    - sidekiq

services:
  website:
    <<: *shared-config
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b '0.0.0.0'"
    ports:
      - 3000:3000
      - 4000:4000
    networks:
      - gateway
    environment:
      SELENIUM_REMOTE_URL: http://chrome:3333/wd/hub
    volumes:
      - '.:/website'
  sidekiq:
    image: trader-app_website
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - ./docker/.env
    volumes:
      - '.:/website'
    depends_on:
      - redis
    networks:
      - gateway
    
  postgres:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    env_file:
      - ./docker/postgres/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - gateway
  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - gateway
volumes:
  base_cache_rails:
  base_gems:
  base_packs:
  postgres:
  redis:

networks:
  gateway: {}